// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJI8rD-Cg8kwILNV_7cnhFx3EUb4Z2ZVY',
    appId: '1:541706800377:web:a40bd46181f4f6005a6628',
    messagingSenderId: '541706800377',
    projectId: 'auth-fa8ea',
    authDomain: 'auth-fa8ea.firebaseapp.com',
    storageBucket: 'auth-fa8ea.appspot.com',
    measurementId: 'G-EYZYX1FV3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQkn4WrsScXOwE1A1LZ_rfVDminK0mapk',
    appId: '1:541706800377:android:5d379eb7d66ce99f5a6628',
    messagingSenderId: '541706800377',
    projectId: 'auth-fa8ea',
    storageBucket: 'auth-fa8ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA1Al5zy3NEhdFsRQisvFyBTKvak4148s',
    appId: '1:541706800377:ios:b6de8742405f5d415a6628',
    messagingSenderId: '541706800377',
    projectId: 'auth-fa8ea',
    storageBucket: 'auth-fa8ea.appspot.com',
    iosClientId: '541706800377-majst3t56bjp2jjatftt0ug9rv0sm51j.apps.googleusercontent.com',
    iosBundleId: 'com.example.post',
  );
}
